version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "1323:1323"
    # environment:
    # - API_ENV="dev"
    # - API_PORT="1323"
    # - API_HTTPS=""